# Generated by Django 6.0.6 on 2026-06-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("basic_computer", "Basic Computer Skills"),
                            (
                                "Python-Django Full Course",
                                "Python-Django Full Stack Web Development",
                            ),
                            (
                                "Ai Full Course with Prompt Engineering",
                                "AI Full Course From Promopt Engineering to Practical AI Workflows",
                            ),
                            ("digital_marketing", "Digital Marketing Full Course"),
                            ("SMMA", "Social Media Marketing Agency(SMMA)"),
                            ("Video Editing", "Video Editing With CapCut"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
