# Generated by Django 6.0.6 on 2026-06-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        upload_to="profile/", verbose_name="Profile Photo"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        default="Getachew Zemicheal Hadgu", max_length=150
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile Photo",
                "verbose_name_plural": "Profile Photo",
            },
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="training_type",
            field=models.CharField(
                choices=[
                    ("basic_computer", "Basic Computer Skills"),
                    (
                        "Python-Django Full Course",
                        "Python-Django Full Stack Web Development",
                    ),
                    (
                        "Ai Full Course with Prompt Engineering",
                        "AI Full Course From Prompt Engineering to Practical AI Workflows",
                    ),
                    ("digital_marketing", "Digital Marketing Full Course"),
                    ("SMMA", "Social Media Marketing Agency (SMMA)"),
                    ("Video Editing", "Video Editing With CapCut"),
                ],
                max_length=60,
            ),
        ),
    ]
