# Generated by Django 6.0.6 on 2026-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_profilephoto_alter_bookingrequest_training_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv_file",
                    models.FileField(upload_to="cv/", verbose_name="CV File (PDF)"),
                ),
                (
                    "label",
                    models.CharField(
                        default="Getachew Zemicheal Hadgu - CV", max_length=100
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CV File",
                "verbose_name_plural": "CV File",
            },
        ),
    ]
