# Generated by Django 6.0.6 on 2026-07-04 10:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_cvfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvfile",
            name="cv_file",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="CV File (PDF)"
            ),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="Profile Photo"
            ),
        ),
    ]
